__tests__/unit/component-generators.ts
__tests__/unit/project-generators.ts
src/component-generators/react/react-all.ts
src/component-generators/react/react-component.ts
src/component-generators/vue/vue-component.ts

because the addMapping, addPlugin methods were exposed on the generator instance, their this was not properly pointing to the resolver/assembly line instances
fix #3

fix(component generators): bind exposed methods to preserve 'this'

---

src/core/builder/generators/html-to-string.ts
src/core/builder/generators/js-ast-to-code.ts

postcss prettier plugin added to html-to-string and js-ast-to-code
formats css in js, as well as css in generated html files

fix for unformatted css in generated html and js files

---

package-lock.json

Just a small package lock update as I noticed there was a security vulnerability pointed out by running `npm install` in the master branch.

Bump version of js-yaml to avoid security warning

---

__tests__/integration/component-assignemnts/attribute-value.ts
__tests__/integration/component-assignemnts/component-with-valid-attr-prop.json
src/plugins/teleport-plugin-vue-base-component/utils.ts
src/shared/utils/ast-js-utils.ts

Allows for assignments like:
```
"data-inner-value": {
"type": "dynamic",
"content": {
"referenceType":"prop",
"id": "content.heading"
}
}
```
in both vue and react generators

WIP: Feature/#112 object referinging in dynamic assignments

---

__tests__/unit/shared/utils/ast-jsx-utils.ts
examples/uidl-samples/new-project.json
src/plugins/teleport-plugin-react-base-component/utils.ts
src/shared/utils/ast-jsx-utils.ts
src/typings/generators.d.ts

until now only state was allowed
closes #75

feat(conditional render): support props as conditional identifier

---

src/shared/utils/project-utils.ts

The project generator errors only logged the name of the error, not what happened and where. This is a one liner that helps me see better errors.

refactor(Better project error): Full stack trace log

---

packages/teleport-generator-core/src/uidl-schemas/component.json

fixes #12
This is the example that i generated after assigning arraya
~~~
SimpleComponent.defaultProps = {
test: [
{
name: 'sdnfdksjfn',
},
{
number: 'dsfndsn',
},
],
}
SimpleComponent.propTypes = {
test: PropTypes.array,
}
~~~

refactor(generator-core): Schema to support array as  a default value

---

examples/uidl-samples/project.json
packages/teleport-generator-core/__tests__/resolver/utils.ts
packages/teleport-generator-core/src/resolver/index.ts
packages/teleport-generator-core/src/resolver/utils.ts
packages/teleport-generator-shared/src/typings/generators.ts
packages/teleport-generator-shared/src/utils/project-utils.ts
packages/teleport-project-generator-react-basic/src/index.ts
packages/teleport-project-generator-react-next/src/index.ts
packages/teleport-project-generator-vue-basic/src/index.ts
packages/teleport-project-generator-vue-nuxt/src/index.ts

this is solved at resolve time, based on the state definitions of the route key, which are
accompanied by a meta.path field
closes #189

feat(navlinks): transitionTo can now refer to the state key, not the url

---

lerna.json
package.json

1. Run ``npm run version`` for bumping version and pushing to github.
2. Run ``npm run publish`` for publishing the packages to npm by taking them from github.
For changelog, run ``npm run changelog``
For generating changelog from the beginning of the project ``npm run changelog:start``
The newly added ``command/version/message`` attributes adds the message to the commit by following the commitzen principles, which makes it blend with other commit messages. 😃

chore(lerna.json): Added scripts for version bumping and releases

---

packages/teleport-uidl-validator/src/uidl-schemas/component.json

fix(uidl/comp): Validating content if the parent type is static

---

packages/teleport-component-generator/src/index.ts
packages/teleport-uidl-validator/src/uidl-schemas/component.json

the filename is now taken from the sanitized uidl name. also added a restriction on the elementType
to allow only alphanumeric characters, since the name is taken as a import variable when using
dependencies
fix #235

fix(uidl): filename derived from sanitized component name

---

packages/teleport-component-generator/src/builder/generators/js-ast-to-code.ts
packages/teleport-plugin-import-statements/src/index.ts
packages/teleport-plugin-react-app-routing/package.json
packages/teleport-plugin-react-app-routing/src/index.ts
packages/teleport-plugin-react-app-routing/src/utils.ts
packages/teleport-plugin-react-base-component/src/node-handlers.ts
packages/teleport-plugin-react-base-component/src/utils.ts
packages/teleport-plugin-react-css-modules/package.json
packages/teleport-plugin-react-css-modules/src/index.ts
packages/teleport-plugin-react-inline-styles/package.json
packages/teleport-plugin-react-inline-styles/src/index.ts
packages/teleport-plugin-react-jss/package.json
packages/teleport-plugin-react-jss/src/index.ts
packages/teleport-plugin-react-jss/src/utils.ts
packages/teleport-plugin-react-styled-components/src/index.ts
packages/teleport-plugin-react-styled-jsx/__tests__/utils.ts
packages/teleport-plugin-react-styled-jsx/src/index.ts
packages/teleport-plugin-react-styled-jsx/src/utils.ts
packages/teleport-project-generator-react-next/src/utils.ts
packages/teleport-shared/__tests__/builders/ast-builders.ts
packages/teleport-shared/__tests__/utils/ast-jsx-utils.ts
packages/teleport-shared/src/builders/ast-builders.ts
packages/teleport-shared/src/builders/css-builders.ts
packages/teleport-shared/src/utils/ast-jsx-utils.ts
packages/teleport-types/src/generators.ts

closes #202 and solves some other loose ends.
main goal was to remove direct dependencies to @babel/types in smaller packages. there are still things to be done, but for now it works.

refactor(shared): renames, reusability, tests, cleanup, etc.

---

packages/teleport-shared/__tests__/node-handlers/node-to-jsx/index.ts
packages/teleport-shared/src/builders/uidl-builders.ts
packages/teleport-shared/src/node-handlers/node-to-jsx/index.ts
packages/teleport-types/src/uidl.ts
packages/teleport-uidl-validator/src/parser/index.ts

closes #163 
Unfortunately, it will be tricky to define a behavior that works in both slot cases, because of the different nature of the implementations in react/preact on one side and vue/stencil on the other

fix(slots): restrictions for slot node fallback and separate handling for native / prop based slot

---

packages/teleport-plugin-react-css-modules/__tests__/index.ts
packages/teleport-plugin-react-css-modules/__tests__/mocks.ts
packages/teleport-plugin-react-css-modules/src/index.ts

Solves the problem of generating classes like: `className: {styles['container']}`

refactor(css-modules): classname generation optimization and tests for multiple cases

---

packages/teleport-project-packer/__tests__/index.ts
packages/teleport-project-packer/src/index.ts
packages/teleport-test/src/packer.ts

Hello 👋,
This PR renames the `loadTemplate` method of the packer to `loadRemoteTemplate` as requested [here](https://github.com/teleporthq/teleport-code-generators/issues/377).
EDIT: closes #377

Rename packer.loadTemplate to packer.loadRemoteTemplate

---

packages/teleport-shared/package.json
packages/teleport-shared/src/builders/style-builders.ts
yarn.lock

This PR upgrades the version of `jss` to `10.0.0` ⬆️ by following the official [migration guide](https://cssinjs.org/migrations/?v=v10.0.0).
Closes #374

Upgrade JSS

---

packages/teleport-project-generator-next/src/next-mapping.json
packages/teleport-uidl-resolver/src/utils.ts

This is related to a bug we found in the playground when deploying to next.js, related to styling the navlinks

fix: custom mapping logic for navlinks and <a> tags

---

packages/teleport-project-generator-gatsby/src/index.ts
packages/teleport-project-generator-gatsby/src/project-template.ts
packages/teleport-project-generator-gatsby/src/utils.ts

fixes #397 
I cross-checked and we don't need to make changes for gridsome.

feat(gatsby-proj): support for custom manifest in gatsby

---

packages/teleport-plugin-react-styled-components/src/index.ts

Appending ``Styled`` as a prefix when ``className`` is clashing with the component name or any of its dependencies
fixes #412

fix(styled-comp): appending prefix when name clashes 

---

packages/teleport-plugin-react-styled-jsx/src/index.ts

We have this problem in the playground where a <img> converted into a component will not be styled because the <img> root of the component does not accept <style> as a child node. Hence I made this workaround that surrounds the component in a fragment.

fix: styled-jsx handling self-closing root
