- __tests__/unit/shared/utils/string-utils.ts
- src/core/resolver/index.ts
- src/project-generators/react-basic/index.ts
- src/project-generators/react-next/index.ts
- src/project-generators/vue-basic/index.ts
- src/project-generators/vue-nuxt/index.ts
- src/shared/utils/string-utils.ts
> feat: add sanitize function for component names

- __tests__/performance/react-generator.ts
- __tests__/performance/vue-generator.ts
- __tests__/unit/component-generators.ts
- src/core/builder/generators/html-to-string.ts
- src/core/builder/generators/js-ast-to-code.ts
- src/shared/constants.ts
Added the htmlWhitespaceSensitivity option to avoid bad html formatting
fix #17
> fix(vue formatting): html parser update for prettier

- __tests__/fixtures/react-sample.json
- __tests__/fixtures/uidl.ts
- __tests__/fixtures/vue-sample.json
- examples/uidl-samples/component-author-card.json
- examples/uidl-samples/component-card-list.json
- examples/uidl-samples/component-tab-selector.json
- examples/uidl-samples/project-routing.json
- examples/uidl-samples/project-state-components.json
- examples/uidl-samples/project-todolist.json
- src/core/resolver/utils.ts
- src/plugins/react/react-css-modules/utils.ts
- src/plugins/react/react-inline-styles.ts
- src/plugins/react/react-jss/index.ts
- src/plugins/react/react-styled-jsx.ts
- src/plugins/vue/vue-style-chunk.ts
- src/uidl-definitions/schemas/component.json
- src/uidl-definitions/schemas/project.json
- src/uidl-definitions/types/index.ts
instead of styles, we decided to use style, to be consistent with the DOM
BREAKING CHANGE: UIDLs need to be updated, all the styles keys transformed into style
> refactor(naming): style key in UIDL

- README.md
One more final place to fix the package name.
> docs(README.md): Fixed the module name

- src/uidl-definitions/schemas/component.json
- src/uidl-definitions/schemas/project.json
- src/uidl-definitions/types/index.ts
> refactor(schemas): Updated schemas with enum values

- package-lock.json
- package.json
There was a new security warning that just showed up a couple of hours ago
> fix(Update package json): Fixes security warnings that showed up today

- src/plugins/teleport-plugin-react-base-component/utils.ts
- src/shared/utils/ast-jsx-utils.ts
Added ability to render ternary expressions for boolean
A little bit of cleanup is needed and I am working on here is the [sandbox](https://codesandbox.io/s/jxw2786x5) link where you can refer the ``UIDLSchema`` and code that is generated in ``App.js`` component.
fixes #14
> Ternary Expression for boolean states

- src/plugins/teleport-plugin-vue-base-component/index.ts
- src/plugins/teleport-plugin-vue-base-component/utils.ts
- src/shared/utils/string-utils.ts
> Ternary Expressions for Vue

- src/core/resolver/utils.ts
- src/plugins/teleport-plugin-react-base-component/utils.ts
- src/shared/utils/project-utils.ts
> Fix for #148

- README.md
As we have changed the output format of the code that is generated
> docs(Readme.md): The code output format is generated, so updated Readme

- package-lock.json
- package.json
> chore(package.json): Removed repeat-string as direct dependency

- __tests__/integration/component-assignments/component-with-valid-state-reference.json
- __tests__/integration/component-assignments/style-values.ts
- src/plugins/teleport-plugin-react-css-modules/index.ts
- src/plugins/teleport-plugin-react-inline-styles/index.ts
- src/plugins/teleport-plugin-react-jss/index.ts
fixes #200
In this PR, is for discussion and behavior of the style flavors that we currently have and support.
I have shared a few observation in the issue and then I have played around a little bit with the styles support that we currently have and here are the **fixes** that I made to the styles.
PS: Will update the PR shortly in detail with all the observations and fixes that i am working on
- Implementing #168 into the development pipeline, so we can refer if the component code that is being generated is a valid one.
- Writing test cases for the generated code using [react-testing-library](https://github.com/testing-library/react-testing-library) in that way we can assess the behavior of the component that is being generated, if the styles are being applied or if the component is …
> fix(style-flavours): Fixed style flavours w.r.t to their behaviour

- README.md
Just added ``StyledComponents`` to the list.
> docs(Readme.md): Added StyledComponents to the list of plugins supported

- CHANGELOG.md
Update the changelog, with all the new package system that we introduced with lerna
> docs(changelog.md): Updated the changelog after adopting lerna

- packages/teleport-component-generator-react/__tests__/integration/component-non-element-root.ts
- packages/teleport-generator-core/src/uidl-schemas/component.json
- packages/teleport-generator-shared/src/typings/uidl.ts
- packages/teleport-plugin-react-proptypes/__tests__/index.ts
- packages/teleport-plugin-react-proptypes/src/index.ts
- packages/teleport-plugin-react-proptypes/src/utils.ts
- packages/teleport-plugin-vue-base-component/src/utils.ts
Removed generation of defaultProps if the component doesn't have any defaultValue, for any of the props. And supporting ``isRequired`` attribute for ``propTypes`` definition
fixes #213 fixes #12
> feat(plugin-react-proptypes): Added isRequired attribute for proptypes

- packages/teleport-project-generator-react-basic/src/index.ts
- packages/teleport-project-generator-react-next/src/index.ts
- packages/teleport-project-generator-vue-basic/src/index.ts
- packages/teleport-project-generator-vue-nuxt/src/index.ts
- packages/teleport-project-packer-test/src/index.ts
- packages/teleport-project-packer/__tests__/index.ts
- packages/teleport-project-packer/src/constants.ts
- packages/teleport-project-packer/src/errors.ts
- packages/teleport-project-packer/src/index.ts
- packages/teleport-shared/src/utils/project-utils.ts
- packages/teleport-types/src/generators.ts
> refactor: Set default template to the generic packer

- packages/teleport-publisher-github/src/index.ts
> fix(github-packer): Added master branch and check for commit branch

- packages/teleport-publisher-now/__tests__/index.ts
- packages/teleport-publisher-now/src/errors.ts
- packages/teleport-publisher-now/src/index.ts
> refactor(now/src): Changes the name to accessToken from deployToken

- .gitignore
- README.md
- packages/teleport-project-packer-test/src/config.example.json
- packages/teleport-project-packer-test/src/index.ts
> chore(packer-test): Used a config file to display the github token

- packages/teleport-plugin-react-styled-jsx/__tests__/index.ts
- packages/teleport-plugin-react-styled-jsx/src/index.ts
- packages/teleport-shared/src/utils/uidl-utils.ts
> fix(styled-jsx/index): Injecting style in first child if root is non element

- packages/teleport-github-gateway/src/constants.ts
- packages/teleport-github-gateway/src/utils.ts
> feat: Decode github files using a whitelist

- packages/teleport-component-generator-react/__tests__/integration/component-attrs.ts
- packages/teleport-component-generator-react/src/react-mapping.json
- packages/teleport-component-generator-vue/__tests__/integration/component-attrs.ts
- packages/teleport-component-generator-vue/src/vue-mapping.json
- packages/teleport-component-generator/__tests__/resolver/index.ts
- packages/teleport-component-generator/src/html-mapping.json
- packages/teleport-component-generator/src/resolver/index.ts
- packages/teleport-component-generator/src/resolver/utils.ts
- packages/teleport-types/src/uidl.ts
- packages/teleport-uidl-validator/src/uidl-schemas/component.json
> feat(Attribute-mapping): Adding mapping for attributes

- packages/teleport-component-generator/__tests__/resolver/utils.ts
- packages/teleport-component-generator/package.json
- packages/teleport-component-generator/src/resolver/utils.ts
- yarn.lock
> chore(Component generator): Deepmerge option for mergeMappings

- packages/teleport-project-generator/__tests__/mocks.ts
- packages/teleport-project-generator/__tests__/utils.ts
- packages/teleport-project-generator/src/utils.ts
> fix(proj-gen): check for file override instead of duplication

- packages/teleport-plugin-react-css-modules/src/index.ts
- packages/teleport-plugin-react-inline-styles/src/index.ts
- packages/teleport-plugin-react-jss/src/index.ts
- packages/teleport-plugin-react-styled-components/src/index.ts
- packages/teleport-plugin-react-styled-jsx/src/index.ts
- packages/teleport-plugin-vue-css/src/index.ts
> fix(plugin-styles): Fix generation of empty styles

- packages/teleport-repl-component/src/components/editor/editor.css
- packages/teleport-repl-component/src/components/editor/editor.tsx
- packages/teleport-repl-component/src/index.html
> (feat): Added a tab to show css file

- packages/teleport-component-generator-stencil/src/index.ts
- packages/teleport-component-generator/__tests__/index.ts
- packages/teleport-component-generator/src/index.ts
- packages/teleport-postprocessor-prettier-html/src/index.ts
- packages/teleport-postprocessor-prettier-js/src/index.ts
- packages/teleport-postprocessor-vue-file/src/index.ts
- packages/teleport-shared/src/constants/index.ts
- packages/teleport-types/src/generators.ts
> feat(postprocessors): factory functions defined with options for configurability

- packages/teleport-shared/__tests__/builders/project-builders.ts
- packages/teleport-shared/src/builders/project-builders.ts
> feat(Builders): Added project-builders and tests

- packages/teleport-project-generator-preact/package.json
- packages/teleport-project-generator-preact/src/constants.ts
- packages/teleport-project-generator-preact/src/index.ts
- packages/teleport-project-generator-stencil/src/index.ts
- packages/teleport-project-generator/src/file-handlers.ts
- packages/teleport-types/src/generators.ts
…jecting custom tags
closes #342
> fix(preact-generator): Picking a inbuilt index template and injecting custom tags

- examples/uidl-samples/project.json
- packages/teleport-component-generator/src/resolver/utils.ts
- packages/teleport-plugin-jsx-head-config/__tests__/index.ts
- packages/teleport-plugin-jsx-head-config/src/index.ts
- packages/teleport-plugin-vue-head-config/__tests__/index.ts
- packages/teleport-plugin-vue-head-config/src/index.ts
- packages/teleport-project-generator-next/src/utils.ts
- packages/teleport-project-generator/src/file-handlers.ts
- packages/teleport-project-generator/src/index.ts
- packages/teleport-project-generator/src/utils.ts
- packages/teleport-types/src/uidl.ts
Addresses some leftovers of #21
> refactor(seo): handling default title and canonical link

- packages/teleport-component-generator-angular/__tests__/end2end/index.ts
- packages/teleport-component-generator-vue/__tests__/end2end/index.ts
- packages/teleport-plugin-angular-base-component/src/index.ts
- packages/teleport-plugin-angular-base-component/src/utils.ts
- packages/teleport-plugin-vue-base-component/src/utils.ts
- packages/teleport-project-packer-test/src/index.ts
- packages/teleport-shared/src/builders/uidl-builders.ts
- packages/teleport-shared/src/node-handlers/node-to-html/constants.ts
- packages/teleport-shared/src/node-handlers/node-to-html/types.ts
- packages/teleport-shared/src/node-handlers/node-to-html/utils.ts
- packages/teleport-shared/src/utils/ast-js-utils.ts
> fix(angular-base): Handling multiple statements in event handlers

- packages/teleport-code-generator/package.json
- packages/teleport-code-generator/src/index.ts
- packages/teleport-code-generator/src/types.ts
- packages/teleport-publisher-codesandbox/README.md
- packages/teleport-publisher-codesandbox/package.json
- packages/teleport-publisher-codesandbox/src/constants.ts
- packages/teleport-publisher-codesandbox/src/index.ts
- packages/teleport-publisher-codesandbox/src/utils.ts
- packages/teleport-publisher-codesandbox/tsconfig-cjs.json
- packages/teleport-publisher-codesandbox/tsconfig-esm.json
- packages/teleport-test/package.json
- packages/teleport-test/src/standalone.ts
> feat(publisher): codesandbox integration added

- packages/teleport-plugin-stencil-app-routing/__tests__/index.ts
> test(stencil-app-routing): adding test cases for stencil app routing

- packages/teleport-plugin-stencil-base-component/src/index.ts
> feat(stencil-base): changing title tag for stencil dynamically

- examples/test-samples/component-invalid-sample.json
- examples/test-samples/component-sample.json
- examples/test-samples/project-invalid-sample.json
- examples/test-samples/project-sample.json
- examples/uidl-samples/project.json
- packages/teleport-component-generator-react/src/react-mapping.json
- packages/teleport-component-generator-stencil/src/stencil-mapping.json
- packages/teleport-shared/__tests__/node-handlers/node-to-html/index.ts
- packages/teleport-shared/src/node-handlers/node-to-html/index.ts
- packages/teleport-shared/src/node-handlers/node-to-jsx/index.ts
- packages/teleport-shared/src/utils/uidl-utils.ts
- packages/teleport-types/src/uidl.ts
- packages/teleport-uidl-resolver/__tests__/mapping.json
- packages/teleport-uidl-resolver/__tests__/resolver.ts
- packages/teleport-uidl-resolver/__tests__/utils.ts
- packages/teleport-uidl-resolver/src/html-mapping.json
- packages/teleport-uidl-resolver/src/resolver.ts
- packages/teleport-uidl-resolver/src/utils.ts
- packages/teleport-uidl-validator/src/uidl-schemas/component.json
- scripts/watcher.js
This fixes lots of potential issues and edge cases with the input UIDL
> feat: string blacklists on mappings and regex validation for some strings in the UIDL

- packages/teleport-project-generator-gridsome/src/gridsome-project-mapping.json
> fix(gridsome-mapping): adding mappings for gridsome

- packages/teleport-plugin-angular-module/src/utils.ts
> refactor(module-angular): switching to modern syntax for lazy loading

- packages/teleport-plugin-common/src/node-handlers/node-to-html/index.ts
- packages/teleport-plugin-common/src/node-handlers/node-to-html/utils.ts
- packages/teleport-plugin-common/src/node-handlers/node-to-jsx/index.ts
- packages/teleport-plugin-common/src/utils/ast-utils.ts
- packages/teleport-shared/__tests__/utils/string-utils.ts
- packages/teleport-shared/src/utils/string-utils.ts
> new function for html encoding

- packages/teleport-plugin-angular-base-component/src/utils.ts
- packages/teleport-plugin-angular-module/__tests__/index.ts
- packages/teleport-plugin-angular-module/src/index.ts
- packages/teleport-plugin-angular-module/src/utils.ts
- packages/teleport-publisher-now/src/utils.ts
- packages/teleport-shared/src/utils/uidl-utils.ts
fixes #409 
unfortunately it's not the best solution, but it should work for now
> fix: name cleanup and dependency import in module fix

- packages/teleport-code-generator/__tests__/index.ts
- packages/teleport-code-generator/src/index.ts
- packages/teleport-project-packer/__tests__/index.ts
- packages/teleport-project-packer/src/constants.ts
- packages/teleport-project-packer/src/errors.ts
- packages/teleport-project-packer/src/index.ts
- packages/teleport-publisher-codesandbox/src/index.ts
- packages/teleport-publisher-codesandbox/src/utils.ts
- packages/teleport-publisher-disk/__tests__/index.ts
- packages/teleport-publisher-disk/src/errors.ts
- packages/teleport-publisher-disk/src/index.ts
- packages/teleport-publisher-github/__tests__/index.ts
- packages/teleport-publisher-github/src/errors.ts
- packages/teleport-publisher-github/src/index.ts
- packages/teleport-publisher-now/__tests__/index.ts
- packages/teleport-publisher-now/src/errors.ts
- packages/teleport-publisher-now/src/index.ts
- packages/teleport-publisher-now/src/utils.ts
- packages/teleport-publisher-zip/__tests__/index.ts
- packages/teleport-publisher-zip/src/errors.ts
- packages/teleport-publisher-zip/src/index.ts
- packages/teleport-types/src/errors.ts
- packages/teleport-types/src/generators.ts
- packages/teleport-types/src/index.ts
- packages/teleport-uidl-validator/__tests__/validator/index.ts
- packages/teleport-uidl-validator/src/validator/index.ts
- packages/teleport-uidl-validator/src/validator/utils.ts
- tslint.json
> feat: publishers throw relevant errors

- packages/teleport-project-generator-gatsby/__tests__/end2end/index.ts
- packages/teleport-project-generator-gatsby/package.json
- packages/teleport-project-generator-gatsby/src/index.ts
- packages/teleport-project-generator-gatsby/src/project-template.ts
- packages/teleport-project-generator/package.json
- packages/teleport-project-generator/src/constants.ts
- packages/teleport-project-generator/src/index.ts
- packages/teleport-test/src/packer.ts
- packages/teleport-types/src/generators.ts
- yarn.lock
A Different approach for PR --> https://github.com/teleporthq/teleport-code-generators/pull/386 using `magic-string` for reducing bundle size
> feat(gatsby-proj): project generators can configure a file to change

- package.json
- packages/teleport-component-generator-angular/__tests__/end2end/index.ts
- packages/teleport-plugin-angular-base-component/src/index.ts
- packages/teleport-plugin-common/src/node-handlers/node-to-html/constants.ts
- packages/teleport-plugin-common/src/node-handlers/node-to-html/index.ts
- packages/teleport-plugin-common/src/node-handlers/node-to-html/types.ts
- packages/teleport-plugin-common/src/node-handlers/node-to-jsx/index.ts
- packages/teleport-plugin-common/src/node-handlers/node-to-jsx/types.ts
- packages/teleport-plugin-preact-base-component/src/index.ts
- packages/teleport-plugin-preact-base-component/src/utils.ts
- packages/teleport-plugin-react-base-component/__tests__/index.ts
- packages/teleport-plugin-react-base-component/src/index.ts
- packages/teleport-plugin-react-base-component/src/utils.ts
- packages/teleport-plugin-stencil-base-component/src/index.ts
- packages/teleport-plugin-stencil-base-component/src/utils.ts
- packages/teleport-plugin-vue-base-component/src/index.ts
- packages/teleport-plugin-vue-base-component/src/utils.ts
- packages/teleport-shared/src/utils/string-utils.ts
- packages/teleport-shared/src/utils/uidl-utils.ts
- packages/teleport-types/src/uidl.ts
- packages/teleport-uidl-builders/src/component-builders.ts
- packages/teleport-uidl-validator/src/parser/index.ts
- packages/teleport-uidl-validator/src/uidl-schemas/component.json
> feat(uidl-schema): adding a new raw node for escaping encoding

- README.md
> chore(readme): updating broken article link in readme

- examples/uidl-samples/project.json
- packages/teleport-component-generator-reactnative/src/react-native-mapping.json
- packages/teleport-project-generator-next/src/next-mapping.json
- packages/teleport-shared/src/utils/uidl-utils.ts
- packages/teleport-test/package.json
- packages/teleport-types/src/uidl.ts
- packages/teleport-uidl-resolver/__tests__/abilities/mocks.ts
- packages/teleport-uidl-resolver/__tests__/abilities/utils.ts
- packages/teleport-uidl-resolver/__tests__/utils.ts
- packages/teleport-uidl-resolver/src/html-mapping.json
- packages/teleport-uidl-resolver/src/resolver.ts
- packages/teleport-uidl-resolver/src/resolvers/abilities/index.ts
- packages/teleport-uidl-resolver/src/resolvers/abilities/utils.ts
- packages/teleport-uidl-resolver/src/utils.ts
- packages/teleport-uidl-validator/src/parser/index.ts
- packages/teleport-uidl-validator/src/uidl-schemas/component.json
- yarn.lock
Adding support for the link sub-structure for each element node, which is transformed at resolver time into a link/navlink element wrapping the corresponding node
> feat(link) adding basic support for links on any nodes and resolver functionality

- packages/teleport-code-generator/__tests__/index.ts
- packages/teleport-github-gateway/src/types.ts
- packages/teleport-github-gateway/src/utils.ts
- packages/teleport-project-packer/__tests__/index.ts
- packages/teleport-project-packer/src/utils.ts
- packages/teleport-publisher-codesandbox/src/utils.ts
- packages/teleport-test/src/standalone.ts
- packages/teleport-types/src/generators.ts
> fix: assets handling

- packages/teleport-types/src/uidl.ts
- packages/teleport-uidl-resolver/src/html-mapping.json
- packages/teleport-uidl-resolver/src/resolvers/abilities/utils.ts
- packages/teleport-uidl-resolver/src/utils.ts
- packages/teleport-uidl-validator/src/uidl-schemas/component.json
Add semanticType next to elementType for nodes.
Updates to validation and resolver
> feat: add semantic type
